package com.geekworld.cheava.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.geekworld.cheava.greendao.ScreenWord;
import com.geekworld.cheava.greendao.ScreenImage;

import com.geekworld.cheava.greendao.ScreenWordDao;
import com.geekworld.cheava.greendao.ScreenImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig screenWordDaoConfig;
    private final DaoConfig screenImageDaoConfig;

    private final ScreenWordDao screenWordDao;
    private final ScreenImageDao screenImageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        screenWordDaoConfig = daoConfigMap.get(ScreenWordDao.class).clone();
        screenWordDaoConfig.initIdentityScope(type);

        screenImageDaoConfig = daoConfigMap.get(ScreenImageDao.class).clone();
        screenImageDaoConfig.initIdentityScope(type);

        screenWordDao = new ScreenWordDao(screenWordDaoConfig, this);
        screenImageDao = new ScreenImageDao(screenImageDaoConfig, this);

        registerDao(ScreenWord.class, screenWordDao);
        registerDao(ScreenImage.class, screenImageDao);
    }

    public void clear() {
        screenWordDaoConfig.getIdentityScope().clear();
        screenImageDaoConfig.getIdentityScope().clear();
    }

    public ScreenWordDao getScreenWordDao() {
        return screenWordDao;
    }

    public ScreenImageDao getScreenImageDao() {
        return screenImageDao;
    }

}
