package com.geekworld.cheava.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SCREEN_IMAGE".
 */
public class ScreenImage {

    private Long id;
    /**
     * Not-null value.
     */
    private String imagepath;

    public ScreenImage() {
    }

    public ScreenImage(Long id) {
        this.id = id;
    }

    public ScreenImage(Long id, String imagepath) {
        this.id = id;
        this.imagepath = imagepath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath;
    }

}
