package com.geekworld.cheava.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "SCREEN__CONTENT".
 */
public class Screen_Content {

    private Long id;
    /**
     * Not-null value.
     */
    private String image;
    /**
     * Not-null value.
     */
    private String word;

    public Screen_Content() {
    }

    public Screen_Content(Long id) {
        this.id = id;
    }

    public Screen_Content(Long id, String image, String word) {
        this.id = id;
        this.image = image;
        this.word = word;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getImage() {
        return image;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * Not-null value.
     */
    public String getWord() {
        return word;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setWord(String word) {
        this.word = word;
    }

}
